export const SAMPLE_ACTION = 'SAMPLE_ACTION';

export const SAMPLE_FETCH_REQUEST = 'SAMPLE_FETCH_REQUEST';
export const SAMPLE_FETCH_FAILURE = 'SAMPLE_FETCH_FAILURE';
export const SAMPLE_FETCH_SUCCESS = 'SAMPLE_FETCH_SUCCESS';

export const LOAD_MARKED_RESULT_REQUEST = 'LOAD_MARKED_RESULT_REQUEST';
export const LOAD_MARKED_RESULT_FAILURE = 'LOAD_MARKED_RESULT_FAILURE';
export const LOAD_MARKED_RESULT_SUCCESS = 'LOAD_MARKED_RESULT_SUCCESS';

export const SAVE_MARKED_RESULT_REQUEST = 'SAVE_MARKED_RESULT_REQUEST';
export const SAVE_MARKED_RESULT_FAILURE = 'SAVE_MARKED_RESULT_FAILURE';
export const SAVE_MARKED_RESULT_SUCCESS = 'SAVE_MARKED_RESULT_SUCCESS';
